services:
  http-server:
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    ports:
      - "8000:8000"
    # Load variables from your local .env file
    env_file:
      - .env
    # This allows the container to reach your host machine (laptop)
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ws-server:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
